#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := windowDecorator.cpp testFunctions.cpp MAX7219.cpp

# header files in this project
HEADERS := windowDecorator.hpp testFunctions.hpp MAX7219.hpp

# other places to look for files for this project
SEARCH  := ../MAX7219-Library

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
